### ISSUE TITLE
Add support for Turkish/Arabic/Persian quarter tone accidentals

### ISSUE THREAD

**Issue by infojunkie** [infojunkie/music-l10n#2]
https://github.com/0xfe/vexflow/issues/318

**Comment by infojunkie** [comment]
PR merged to VexFlow.

**Comment by infojunkie** [comment]
Closed this too soon... Arabic 3/4 flat, Persian sori and koron still pending.

**Comment by infojunkie** [comment]
Pending Arabic 3/4 flat

**Comment by infojunkie** [comment]
@Huji, I could use your help to create the missing Arabic 3/4 flat accidental in the Gonville font, as shown on this SMuFL page: https://w3c.github.io/smufl/gitbook/tables/arabic-accidentals.html

Specifically, I'd like to understand how you created the koron and sori accidental shapes and converted them to the JS array. Thanks!

**Comment by Huji** [comment]
I created them using a jsFiddle and trial and error. Unfortunately, I didn't save the jsFiddle link, let me see if I can find it and email it to you.

**Comment by infojunkie** [comment]
I would appreciate any hint about your understanding of the font format - last time I tried, I didn't get very far to understand the numbers that are used for each glyph.

**Comment by infojunkie** [comment]
Here is a fiddle that allows to interactively design a glyph: https://jsfiddle.net/infojunkie/nwyr2zqo/

**Comment by Huji** [comment]
As you can see there, the output is not as "smooth" as what is shown in Vexflow. I remember I had found a way to fix this smoothness issue, but cannot remember how.

Also, you will notice that in your fiddle, vd1 is shown much smaller than vd0. That is another thing you might want to fix. I think one of the parameters in the glyph definition is a scaling factor.
