### ISSUE TITLE
Gonville font missing glyphs for Arabic & Persian accidentals

### ISSUE THREAD

**Issue by infojunkie** [infojunkie/music-l10n#6]
as per https://github.com/0xfe/vexflow/issues/318#issuecomment-194698253:
- Arabic 3 quarters flat
- Persian koron
- Persian sori

**Comment by infojunkie** [comment]
Need to contact Gonville maintainer: http://www.chiark.greenend.org.uk/~sgtatham/gonville/

**Comment by SalahAdDin** [comment]
Will be better change Gonville by SMuFL, won't do?

**Comment by infojunkie** [comment]
SMuFL supports more accidentals, but not the Arabic 3/4 flat.

**Comment by SalahAdDin** [comment]
So, what have to do for put  Arabic 3/4 flat.?

**Comment by infojunkie** [comment]
Ask Gonville and/or SMuFL maintainers to add it :-) But I need to tell you there is some controversy about this symbol, so it's OK to proceed without it for the moment.

**Comment by SalahAdDin** [comment]
Ah, ok. I understand, so, what's the next in your fork?

**Comment by infojunkie** [comment]
My fork is complete with respect to what's available in Gonville and VexFlow. As I mentioned on the VexFlow issue, now I need to add those accidentals to VexTab parser.

**Comment by SalahAdDin** [comment]
But, i think that other accidentals are necessary, i'll put a image with all accidentals that mus2 has.

Ok, here is:
![seleccion_046](https://cloud.githubusercontent.com/assets/5034215/13694703/f8c29bdc-e725-11e5-9818-f84c7573791f.png)
I have the program, tomorrow i can do a list with all symbols in these image and put in vexflow for are a complete, at least Turkish, music notation.

**Comment by infojunkie** [comment]
Thanks for the screenshot! If you notice, the same 3/4 Arabic flat is not there.

Would be great to have a table (e.g. in a Google spreadsheet) comparing available accidentals in existing notation systems and fonts.

**Comment by SalahAdDin** [comment]
here are a list:
![accidentals1](https://cloud.githubusercontent.com/assets/5034215/13722214/ac8bc342-e80b-11e5-801d-b3b16b2042c6.jpg)
![accidentals2](https://cloud.githubusercontent.com/assets/5034215/13722215/ac9e391e-e80b-11e5-9f3d-bd1bb9dc8849.jpg)

**Comment by Huji** [comment]
I reached out to the Gonvile developer and received some info about how to add new glyphs. @infojunkie  did you add the missing ones? If not, let's work together.

**Comment by infojunkie** [comment]
Thanks @SalahAdDin for the list. 

@Huji, I have not added the missing accidentals to Gonville. Can you share here the information you received?

**Comment by Huji** [comment]
It was information received privately via email so even though it doesn't seem to contain sensitive info, I don't feel comfortable sharing an email publicly. I will forward it to your email in a second. We can then decide which parts to share here for the public eye.

**Comment by SalahAdDin** [comment]
But, won't be better use SMuFL fonts instead Gonville fonts?

**Comment by infojunkie** [comment]
@SalahAdDin: yes, using SMuFL on VexFlow will eventually be better - but that doesn't mean Gonville would not benefit from those additions.

**Comment by Huji** [comment]
I agree with @infojunkie and also think that the issue of using SMuFL is a separate issue.

**Comment by infojunkie** [comment]
@Huji I haven't received an email from you. Do you have my email address?

**Comment by Huji** [comment]
Just sent it

**Comment by SalahAdDin** [comment]
uffff gonville doesn't update since two years ago!

**Comment by SalahAdDin** [comment]
What's about this?

**Comment by infojunkie** [comment]
I think Gonville is a dead end: it's non-standard and has very little activity. It's better to contribute to SMuFL integration into VexFlow.

**Comment by SalahAdDin** [comment]
yeah 💃
